# Generated by Django 4.0.2 on 2022-02-15 08:31

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.newuser')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.fields.EmbeddedField(model_container=blog.models.Blog)),
                ('meta_data', djongo.models.fields.EmbeddedField(model_container=blog.models.MetaData)),
                ('headline', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.ManyToManyField(to='blog.Author')),
            ],
        ),
    ]
