# Generated by Django 4.0.2 on 2022-02-15 09:12

import blog.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=djongo.models.fields.EmbeddedField(model_container=blog.models.Blog, model_form_class=blog.models.BlogForm),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_data',
            field=djongo.models.fields.EmbeddedField(model_container=blog.models.MetaData, model_form_class=blog.models.MetaDataForm),
        ),
    ]
